openapi: "3.0.1"
info:
  title: "users"
  version: "2022-07-18 20:18:52UTC"
servers:
- url: "https://ke0q79ybf5.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /userOperations:
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Default response for ANY /userOperations"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${users.Arn}/invocations"
        connectionType: "INTERNET"
x-amazon-apigateway-cors:
  allowMethods:
  - "*"
  allowHeaders:
  - "*"
  exposeHeaders:
  - "*"
  maxAge: 0
  allowCredentials: false
  allowOrigins:
  - "*"
x-amazon-apigateway-importexport-version: "1.0"
