AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Lambda Function for handling all the product API endpoints.

Parameters:
  AntiquelySNSTopicName:
    Type: String
    Default: 'AntiquelySNS'
    Description: Antiquely SNS Topic Name
  AntiquelySNSDisplayName:
    Type: String
    Default: 'Bid Winner'
    Description: Antiquely SNS Display Name
  AntiquelyLabRole:
    Type: String
    Default: 'arn:aws:iam::103757046369:role/LabRole' # Change Lab Role
    Description: Default Lab Role used to create resources
  S3TemplateBucketName:
    Type: String
    Default: antiquely-templates-bharat # Change S3 Bucket name
    Description: Default templates residing bucket parameter
  UsersPartitionKeyName:
    Type: String
    Default: user_id
    Description: Hash Key Name
  UsersPartitionKeyType:
    Type: String
    Default: S
    Description: Hash Key Type
  ProductsPartitionKeyName:
    Type: String
    Default: product_id
    Description: Hash Key Name
  ProductsPartitionKeyType:
    Type: String
    Default: S
    Description: Hash Key Type
  BidsPartitionKeyName:
    Type: String
    Default: bid_id
    Description: Hash Key Name
  BidsPartitionKeyType:
    Type: String
    Default: S
    Description: Hash Key Type

Resources:
  # This call is for creating a lambda function for decider
  decider:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "decider-test"
      Handler: decider.handler
      Runtime: nodejs16.x
      CodeUri: 
        Bucket: !Ref S3TemplateBucketName
        Key: lambda/decider.js.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: !Ref AntiquelyLabRole

  product:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "products-test"
      Handler: products.handler
      Runtime: nodejs16.x
      CodeUri: 
        Bucket: !Ref S3TemplateBucketName
        Key: lambda/products.js.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: !Ref AntiquelyLabRole
      Environment:
        Variables: 
          DeciderArn: !GetAtt decider.Arn
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            # EndpointConfiguration:
              # Type: REGIONAL
            # Cors:
            #   AllowHeaders: "*"
            #   AllowMethods: "*"
            #   AllowOrigin: "*"
            Path: /product/handler
            Method: ANY

  
  