AWSTemplateFormatVersion: '2010-09-09'
Parameters:

  S3ProductsImageBucketName:
    Type: String
    Default: antiquely-production-images2
    Description: Default bucket to upload code for deployment
  
Resources:
  S3ProductImageBucket:
    Type: 'AWS::S3::Bucket'
    Description: Bucket on which we will attach and test bucket policy
    Properties:
      BucketName: !Ref S3ProductsImageBucketName
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
          
  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3ProductImageBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${S3ProductImageBucket}'
              - !Sub 'arn:aws:s3:::${S3ProductImageBucket}/*'
            Principal:
              AWS:
                - '*'